--- #YAML:1.0
name:               MooseX-Types-DateTime
version:            0.05
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:            0.4302
    DateTime::Locale:    0.4001
    DateTime::TimeZone:  0.95
    Moose:               0.41
    MooseX::Types:       0.19
    namespace::clean:    0.08
    Test::Exception:     0.27
    Test::use::ok:       0.02
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
